In [66]:
import pandas as pd
import numpy as np

In [67]:
import py_vollib as pv

In [68]:
data = pd.read_parquet('bnf_20221230.parquet')

In [69]:
data

,close,date,high,low,oi,open,symbol,time,volume
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802
1,3.55,2022-12-30,3.6,3.5,60900.0,3.55,BANKNIFTY05JAN2336500PE,09:16:00,30600
2,3.7,2022-12-30,3.7,3.55,107150.0,3.6,BANKNIFTY05JAN2336500PE,09:17:00,21500
3,3.65,2022-12-30,3.7,3.6,107150.0,3.7,BANKNIFTY05JAN2336500PE,09:18:00,11275
4,3.55,2022-12-30,3.65,3.55,107150.0,3.6,BANKNIFTY05JAN2336500PE,09:19:00,14800
...,...,...,...,...,...,...,...,...,...
38753,43037.7,2022-12-30,43074.5,43032.6,nan,43067.65,BANKNIFTY,15:25:00,0
38754,43077.0,2022-12-30,43080.45,43035.2,nan,43035.2,BANKNIFTY,15:26:00,0
38755,43075.3,2022-12-30,43094.95,43075.1,nan,43079.75,BANKNIFTY,15:27:00,0
38756,43034.15,2022-12-30,43080.85,43030.25,nan,43073.15,BANKNIFTY,15:28:00,0
38757,43038.5,2022-12-30,43049.0,43022.85,nan,43034.5,BANKNIFTY,15:29:00,0

In [70]:
data['time'][0]

'09:15:00'

In [93]:
underlying_price = float(data[data['symbol'] == 'BANKNIFTY-I'][data['time'] == '09:15:00']['close'].values[0])

C:\Users\user\AppData\Local\Temp\ipykernel_41720\46371407.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  underlying_price = float(data[data['symbol'] == 'BANKNIFTY-I'][data['time'] == '09:15:00']['close'].values[0])

In [72]:
df = data[data['time'] == '09:15:00']

In [73]:
df

,close,date,high,low,oi,open,symbol,time,volume
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802
350,3.9,2022-12-30,4.95,3.9,248875.0,4.8,BANKNIFTY05JAN2337000PE,09:15:00,35501
677,4.75,2022-12-30,5.9,4.65,97800.0,5.75,BANKNIFTY05JAN2337500PE,09:15:00,22227
972,5.4,2022-12-30,6.65,5.3,307325.0,6.6,BANKNIFTY05JAN2338000PE,09:15:00,65901
1331,6.3,2022-12-30,7.55,6.3,482225.0,7.45,BANKNIFTY05JAN2338500PE,09:15:00,42626
...,...,...,...,...,...,...,...,...,...
36982,3.6,2022-12-30,3.65,3.35,39150.0,3.5,BANKNIFTY05JAN2348000CE,09:15:00,29277
37314,3.5,2022-12-30,3.5,3.2,46275.0,3.2,BANKNIFTY05JAN2348500CE,09:15:00,37576
37638,3.45,2022-12-30,3.5,3.0,313250.0,3.15,BANKNIFTY05JAN2349000CE,09:15:00,200152
38007,43542.0,2022-12-30,43606.1484,43501.0508,2202450.0,43501.0508,BANKNIFTY-I,09:15:00,74453
38383,43343.7,2022-12-30,43422.95,43337.2,nan,43401.7,BANKNIFTY,09:15:00,0

In [74]:
df['symbol'].values

array(['BANKNIFTY05JAN2336500PE', 'BANKNIFTY05JAN2337000PE',
       'BANKNIFTY05JAN2337500PE', 'BANKNIFTY05JAN2338000PE',
       'BANKNIFTY05JAN2338500PE', 'BANKNIFTY05JAN2339000PE',
       'BANKNIFTY05JAN2339500PE', 'BANKNIFTY05JAN2339700PE',
       'BANKNIFTY05JAN2339800PE', 'BANKNIFTY05JAN2339900PE',
       'BANKNIFTY05JAN2340000PE', 'BANKNIFTY05JAN2340100PE',
       'BANKNIFTY05JAN2340200PE', 'BANKNIFTY05JAN2340300PE',
       'BANKNIFTY05JAN2340400PE', 'BANKNIFTY05JAN2340500PE',
       'BANKNIFTY05JAN2340600PE', 'BANKNIFTY05JAN2340700PE',
       'BANKNIFTY05JAN2340800PE', 'BANKNIFTY05JAN2340900PE',
       'BANKNIFTY05JAN2341000PE', 'BANKNIFTY05JAN2341100PE',
       'BANKNIFTY05JAN2341200PE', 'BANKNIFTY05JAN2341300CE',
       'BANKNIFTY05JAN2341300PE', 'BANKNIFTY05JAN2341400PE',
       'BANKNIFTY05JAN2341500CE', 'BANKNIFTY05JAN2341500PE',
       'BANKNIFTY05JAN2341600PE', 'BANKNIFTY05JAN2341700PE',
       'BANKNIFTY05JAN2341800PE', 'BANKNIFTY05JAN2341900PE',
       'BANKNIFTY05JAN2342000CE', 'BANKNIFTY05JAN2342000PE',
       'BANKNIFTY05JAN2342100CE', 'BANKNIFTY05JAN2342100PE',
       'BANKNIFTY05JAN2342200CE', 'BANKNIFTY05JAN2342200PE',
       'BANKNIFTY05JAN2342300CE', 'BANKNIFTY05JAN2342300PE',
       'BANKNIFTY05JAN2342400CE', 'BANKNIFTY05JAN2342400PE',
       'BANKNIFTY05JAN2342500CE', 'BANKNIFTY05JAN2342500PE',
       'BANKNIFTY05JAN2342600CE', 'BANKNIFTY05JAN2342600PE',
       'BANKNIFTY05JAN2342700CE', 'BANKNIFTY05JAN2342700PE',
       'BANKNIFTY05JAN2342800CE', 'BANKNIFTY05JAN2342800PE',
       'BANKNIFTY05JAN2342900CE', 'BANKNIFTY05JAN2342900PE',
       'BANKNIFTY05JAN2343000CE', 'BANKNIFTY05JAN2343000PE',
       'BANKNIFTY05JAN2343100CE', 'BANKNIFTY05JAN2343100PE',
       'BANKNIFTY05JAN2343200CE', 'BANKNIFTY05JAN2343200PE',
       'BANKNIFTY05JAN2343300CE', 'BANKNIFTY05JAN2343300PE',
       'BANKNIFTY05JAN2343400CE', 'BANKNIFTY05JAN2343400PE',
       'BANKNIFTY05JAN2343500CE', 'BANKNIFTY05JAN2343500PE',
       'BANKNIFTY05JAN2343600CE', 'BANKNIFTY05JAN2343600PE',
       'BANKNIFTY05JAN2343700CE', 'BANKNIFTY05JAN2343700PE',
       'BANKNIFTY05JAN2343800CE', 'BANKNIFTY05JAN2343800PE',
       'BANKNIFTY05JAN2343900CE', 'BANKNIFTY05JAN2343900PE',
       'BANKNIFTY05JAN2344000CE', 'BANKNIFTY05JAN2344000PE',
       'BANKNIFTY05JAN2344100CE', 'BANKNIFTY05JAN2344100PE',
       'BANKNIFTY05JAN2344200CE', 'BANKNIFTY05JAN2344200PE',
       'BANKNIFTY05JAN2344300CE', 'BANKNIFTY05JAN2344300PE',
       'BANKNIFTY05JAN2344400CE', 'BANKNIFTY05JAN2344400PE',
       'BANKNIFTY05JAN2344500CE', 'BANKNIFTY05JAN2344500PE',
       'BANKNIFTY05JAN2344600CE', 'BANKNIFTY05JAN2344600PE',
       'BANKNIFTY05JAN2344700CE', 'BANKNIFTY05JAN2344800CE',
       'BANKNIFTY05JAN2344800PE', 'BANKNIFTY05JAN2344900CE',
       'BANKNIFTY05JAN2345000CE', 'BANKNIFTY05JAN2345000PE',
       'BANKNIFTY05JAN2345100CE', 'BANKNIFTY05JAN2345200CE',
       'BANKNIFTY05JAN2345300CE', 'BANKNIFTY05JAN2345400CE',
       'BANKNIFTY05JAN2345500CE', 'BANKNIFTY05JAN2345600CE',
       'BANKNIFTY05JAN2345700CE', 'BANKNIFTY05JAN2345800CE',
       'BANKNIFTY05JAN2345900CE', 'BANKNIFTY05JAN2346000CE',
       'BANKNIFTY05JAN2346500CE', 'BANKNIFTY05JAN2347000CE',
       'BANKNIFTY05JAN2347500CE', 'BANKNIFTY05JAN2348000CE',
       'BANKNIFTY05JAN2348500CE', 'BANKNIFTY05JAN2349000CE',
       'BANKNIFTY-I', 'BANKNIFTY'], dtype=object)

In [75]:
df = df[~df['symbol'].isin(['BANKNIFTY-I', 'BANKNIFTY'])]

In [76]:
df

,close,date,high,low,oi,open,symbol,time,volume
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802
350,3.9,2022-12-30,4.95,3.9,248875.0,4.8,BANKNIFTY05JAN2337000PE,09:15:00,35501
677,4.75,2022-12-30,5.9,4.65,97800.0,5.75,BANKNIFTY05JAN2337500PE,09:15:00,22227
972,5.4,2022-12-30,6.65,5.3,307325.0,6.6,BANKNIFTY05JAN2338000PE,09:15:00,65901
1331,6.3,2022-12-30,7.55,6.3,482225.0,7.45,BANKNIFTY05JAN2338500PE,09:15:00,42626
...,...,...,...,...,...,...,...,...,...
36263,4.05,2022-12-30,4.15,3.8,392775.0,3.85,BANKNIFTY05JAN2347000CE,09:15:00,64576
36635,3.75,2022-12-30,3.75,3.4,20850.0,3.65,BANKNIFTY05JAN2347500CE,09:15:00,19901
36982,3.6,2022-12-30,3.65,3.35,39150.0,3.5,BANKNIFTY05JAN2348000CE,09:15:00,29277
37314,3.5,2022-12-30,3.5,3.2,46275.0,3.2,BANKNIFTY05JAN2348500CE,09:15:00,37576
37638,3.45,2022-12-30,3.5,3.0,313250.0,3.15,BANKNIFTY05JAN2349000CE,09:15:00,200152

In [77]:
call_915 = df[~df['symbol'].str.endswith('PE')]
put_915 = df[df['symbol'].str.endswith('PE')]

In [78]:
call_915.head()

,close,date,high,low,oi,open,symbol,time,volume
8599,2093.15,2022-12-30,2093.15,2093.15,1800.0,2093.15,BANKNIFTY05JAN2341300CE,09:15:00,26
9363,1914.2,2022-12-30,1984.6,1850.0,53675.0,1850.0,BANKNIFTY05JAN2341500CE,09:15:00,1826
11712,1430.5,2022-12-30,1494.25,1400.0,122725.0,1400.0,BANKNIFTY05JAN2342000CE,09:15:00,8577
12452,1352.1,2022-12-30,1392.95,1300.0,14900.0,1300.0,BANKNIFTY05JAN2342100CE,09:15:00,176
13038,1250.85,2022-12-30,1273.1,1246.85,29825.0,1246.85,BANKNIFTY05JAN2342200CE,09:15:00,1176

In [79]:
put_915.head()

,close,date,high,low,oi,open,symbol,time,volume
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802
350,3.9,2022-12-30,4.95,3.9,248875.0,4.8,BANKNIFTY05JAN2337000PE,09:15:00,35501
677,4.75,2022-12-30,5.9,4.65,97800.0,5.75,BANKNIFTY05JAN2337500PE,09:15:00,22227
972,5.4,2022-12-30,6.65,5.3,307325.0,6.6,BANKNIFTY05JAN2338000PE,09:15:00,65901
1331,6.3,2022-12-30,7.55,6.3,482225.0,7.45,BANKNIFTY05JAN2338500PE,09:15:00,42626

In [80]:
import datetime

# Extract necessary columns from the DataFrame
call_option_data = df[df['symbol'].str.endswith('CE')].copy()
call_option_data['time_to_expiration'] = None

# Calculate time to expiration for each call option
for index, row in call_option_data.iterrows():
    symbol = row['symbol']
    expiration_date_str = symbol[9:16]
    expiration_date = datetime.datetime.strptime(expiration_date_str, '%d%b%y').date()

    current_date_str = row['date']
    current_date = datetime.datetime.strptime(current_date_str, '%Y-%m-%d').date()

    time_to_expiration = (expiration_date - current_date).days
    call_option_data.loc[index, 'time_to_expiration'] = time_to_expiration

call_option_data[['symbol', 'time_to_expiration']].head()

                        symbol time_to_expiration
8599   BANKNIFTY05JAN2341300CE                  6
9363   BANKNIFTY05JAN2341500CE                  6
11712  BANKNIFTY05JAN2342000CE                  6
12452  BANKNIFTY05JAN2342100CE                  6
13038  BANKNIFTY05JAN2342200CE                  6

In [81]:
call_option_data.head()

,close,date,high,low,oi,open,symbol,time,volume,time_to_expiration
8599,2093.15,2022-12-30,2093.15,2093.15,1800.0,2093.15,BANKNIFTY05JAN2341300CE,09:15:00,26,6
9363,1914.2,2022-12-30,1984.6,1850.0,53675.0,1850.0,BANKNIFTY05JAN2341500CE,09:15:00,1826,6
11712,1430.5,2022-12-30,1494.25,1400.0,122725.0,1400.0,BANKNIFTY05JAN2342000CE,09:15:00,8577,6
12452,1352.1,2022-12-30,1392.95,1300.0,14900.0,1300.0,BANKNIFTY05JAN2342100CE,09:15:00,176,6
13038,1250.85,2022-12-30,1273.1,1246.85,29825.0,1246.85,BANKNIFTY05JAN2342200CE,09:15:00,1176,6

In [104]:
import py_vollib.black_scholes.implied_volatility as iv
import datetime
import numpy as np

call_option_data = df[df['symbol'].str.endswith('CE')].copy()
call_option_data['implied_volatility'] = 0.2

for index, row in call_option_data.iterrows():
    option_price = float(row['close'])
    stock_price = float(underlying_price)
    strike_price = float(row['symbol'].split('CE')[0][-5:])
    expiration_date_str = row['symbol'][9:16]
    expiration_date = datetime.datetime.strptime(expiration_date_str, '%d%b%y').date()
    current_date = datetime.datetime.strptime(row['date'], '%Y-%m-%d').date()
    time_to_expiration = (expiration_date - current_date).days / 365.0
    risk_free_rate = 0.065  
    initial_guess = 0.2  # Initial estimate of implied volatility

    try:
        implied_volatility = iv.implied_volatility(option_price, stock_price, strike_price, time_to_expiration, risk_free_rate, 'c')
        if np.isnan(implied_volatility):
            continue
        call_option_data.loc[index, 'implied_volatility'] = implied_volatility
    except:
        continue

# Print the resulting DataFrame with implied volatility values
print(call_option_data[['symbol', 'implied_volatility']])

                        symbol  implied_volatility
8599   BANKNIFTY05JAN2341300CE            0.200000
9363   BANKNIFTY05JAN2341500CE            0.200000
11712  BANKNIFTY05JAN2342000CE            0.200000
12452  BANKNIFTY05JAN2342100CE            0.200000
13038  BANKNIFTY05JAN2342200CE            0.200000
13730  BANKNIFTY05JAN2342300CE            0.200000
14434  BANKNIFTY05JAN2342400CE            0.200000
15156  BANKNIFTY05JAN2342500CE            0.200000
15907  BANKNIFTY05JAN2342600CE            0.200000
16657  BANKNIFTY05JAN2342700CE            0.200000
17408  BANKNIFTY05JAN2342800CE            0.200000
18160  BANKNIFTY05JAN2342900CE            0.200000
18912  BANKNIFTY05JAN2343000CE            0.054541
19664  BANKNIFTY05JAN2343100CE            0.085583
20416  BANKNIFTY05JAN2343200CE            0.097299
21168  BANKNIFTY05JAN2343300CE            0.105204
21920  BANKNIFTY05JAN2343400CE            0.110738
22672  BANKNIFTY05JAN2343500CE            0.115810
23423  BANKNIFTY05JAN2343600CE            0.119480
24173  BANKNIFTY05JAN2343700CE            0.121906
24924  BANKNIFTY05JAN2343800CE            0.124447
25674  BANKNIFTY05JAN2343900CE            0.126012
26414  BANKNIFTY05JAN2344000CE            0.127445
27165  BANKNIFTY05JAN2344100CE            0.130075
27819  BANKNIFTY05JAN2344200CE            0.131798
28436  BANKNIFTY05JAN2344300CE            0.133244
28950  BANKNIFTY05JAN2344400CE            0.135481
29443  BANKNIFTY05JAN2344500CE            0.137195
30100  BANKNIFTY05JAN2344600CE            0.138418
30489  BANKNIFTY05JAN2344700CE            0.140183
30872  BANKNIFTY05JAN2344800CE            0.142961
31254  BANKNIFTY05JAN2344900CE            0.145795
31630  BANKNIFTY05JAN2345000CE            0.148562
32158  BANKNIFTY05JAN2345100CE            0.152225
32536  BANKNIFTY05JAN2345200CE            0.155797
32916  BANKNIFTY05JAN2345300CE            0.160707
33297  BANKNIFTY05JAN2345400CE            0.165300
33671  BANKNIFTY05JAN2345500CE            0.169876
34063  BANKNIFTY05JAN2345600CE            0.174517
34437  BANKNIFTY05JAN2345700CE            0.179501
34796  BANKNIFTY05JAN2345800CE            0.184583
35155  BANKNIFTY05JAN2345900CE            0.189624
35510  BANKNIFTY05JAN2346000CE            0.194429
35895  BANKNIFTY05JAN2346500CE            0.220890
36263  BANKNIFTY05JAN2347000CE            0.246312
36635  BANKNIFTY05JAN2347500CE            0.273780
36982  BANKNIFTY05JAN2348000CE            0.301442
37314  BANKNIFTY05JAN2348500CE            0.328756
37638  BANKNIFTY05JAN2349000CE            0.355914

In [105]:
call_option_data

,close,date,high,low,oi,open,symbol,time,volume,implied_volatility
8599,2093.15,2022-12-30,2093.15,2093.15,1800.0,2093.15,BANKNIFTY05JAN2341300CE,09:15:00,26,0.200000
9363,1914.2,2022-12-30,1984.6,1850.0,53675.0,1850.0,BANKNIFTY05JAN2341500CE,09:15:00,1826,0.200000
11712,1430.5,2022-12-30,1494.25,1400.0,122725.0,1400.0,BANKNIFTY05JAN2342000CE,09:15:00,8577,0.200000
12452,1352.1,2022-12-30,1392.95,1300.0,14900.0,1300.0,BANKNIFTY05JAN2342100CE,09:15:00,176,0.200000
13038,1250.85,2022-12-30,1273.1,1246.85,29825.0,1246.85,BANKNIFTY05JAN2342200CE,09:15:00,1176,0.200000
13730,1158.45,2022-12-30,1207.25,1142.2,23125.0,1165.2,BANKNIFTY05JAN2342300CE,09:15:00,1101,0.200000
14434,1064.0,2022-12-30,1128.9,1064.0,23300.0,1072.3,BANKNIFTY05JAN2342400CE,09:15:00,1727,0.200000
15156,980.0,2022-12-30,1040.0,941.4,282250.0,941.4,BANKNIFTY05JAN2342500CE,09:15:00,27901,0.200000
15907,895.0,2022-12-30,946.8,805.35,108725.0,805.35,BANKNIFTY05JAN2342600CE,09:15:00,5276,0.200000
16657,813.6,2022-12-30,868.8,782.4,124000.0,782.4,BANKNIFTY05JAN2342700CE,09:15:00,12401,0.200000
17408,734.6,2022-12-30,788.05,722.3,169200.0,723.95,BANKNIFTY05JAN2342800CE,09:15:00,19627,0.200000
18160,659.9,2022-12-30,713.8,629.15,127325.0,635.0,BANKNIFTY05JAN2342900CE,09:15:00,34452,0.200000
18912,590.9,2022-12-30,638.0,550.0,993550.0,550.0,BANKNIFTY05JAN2343000CE,09:15:00,231678,0.054541
19664,525.6,2022-12-30,567.6,496.1,280325.0,554.85,BANKNIFTY05JAN2343100CE,09:15:00,95928,0.085583
20416,463.1,2022-12-30,500.0,419.95,440475.0,419.95,BANKNIFTY05JAN2343200CE,09:15:00,294502,0.097299
21168,405.4,2022-12-30,441.6,375.05,543150.0,375.05,BANKNIFTY05JAN2343300CE,09:15:00,503103,0.105204
21920,351.65,2022-12-30,384.6,320.9,382875.0,360.0,BANKNIFTY05JAN2343400CE,09:15:00,891278,0.110738
22672,304.3,2022-12-30,332.55,266.5,1274125.0,299.75,BANKNIFTY05JAN2343500CE,09:15:00,996528,0.115810
23423,260.45,2022-12-30,284.9,220.45,166925.0,221.6,BANKNIFTY05JAN2343600CE,09:15:00,503152,0.119480
24173,219.8,2022-12-30,241.8,182.4,223150.0,205.1,BANKNIFTY05JAN2343700CE,09:15:00,242703,0.121906
24924,184.9,2022-12-30,203.2,152.7,303650.0,170.0,BANKNIFTY05JAN2343800CE,09:15:00,237428,0.124447
25674,153.0,2022-12-30,169.05,116.6,196850.0,116.65,BANKNIFTY05JAN2343900CE,09:15:00,183652,0.126012
26414,125.55,2022-12-30,138.9,110.25,831550.0,120.0,BANKNIFTY05JAN2344000CE,09:15:00,475453,0.127445
27165,104.45,2022-12-30,113.9,53.35,214700.0,53.35,BANKNIFTY05JAN2344100CE,09:15:00,139077,0.130075
27819,85.3,2022-12-30,93.15,75.55,305750.0,79.1,BANKNIFTY05JAN2344200CE,09:15:00,159577,0.131798
28436,68.95,2022-12-30,75.55,53.85,200825.0,53.85,BANKNIFTY05JAN2344300CE,09:15:00,182026,0.133244
28950,56.45,2022-12-30,61.45,45.0,121850.0,45.0,BANKNIFTY05JAN2344400CE,09:15:00,123477,0.135481
29443,45.55,2022-12-30,50.7,40.0,845125.0,42.0,BANKNIFTY05JAN2344500CE,09:15:00,261603,0.137195
30100,36.15,2022-12-30,40.5,31.95,124525.0,38.35,BANKNIFTY05JAN2344600CE,09:15:00,108227,0.138418
30489,29.0,2022-12-30,33.55,27.0,124075.0,27.0,BANKNIFTY05JAN2344700CE,09:15:00,123903,0.140183
30872,23.95,2022-12-30,28.25,19.1,154925.0,25.05,BANKNIFTY05JAN2344800CE,09:15:00,71603,0.142961
31254,19.85,2022-12-30,22.0,18.05,62625.0,18.2,BANKNIFTY05JAN2344900CE,09:15:00,48478,0.145795
31630,16.45,2022-12-30,20.0,15.15,704250.0,20.0,BANKNIFTY05JAN2345000CE,09:15:00,213253,0.148562
32158,14.1,2022-12-30,19.0,13.65,37350.0,15.05,BANKNIFTY05JAN2345100CE,09:15:00,20927,0.152225
32536,12.1,2022-12-30,14.5,11.85,152750.0,12.05,BANKNIFTY05JAN2345200CE,09:15:00,43226,0.155797
32916,10.95,2022-12-30,12.7,8.55,85125.0,10.0,BANKNIFTY05JAN2345300CE,09:15:00,32951,0.160707
33297,9.85,2022-12-30,10.95,8.75,25400.0,8.75,BANKNIFTY05JAN2345400CE,09:15:00,37801,0.165300
33671,8.9,2022-12-30,9.35,7.55,284850.0,8.75,BANKNIFTY05JAN2345500CE,09:15:00,143126,0.169876
34063,8.1,2022-12-30,8.75,7.6,24375.0,8.0,BANKNIFTY05JAN2345600CE,09:15:00,15651,0.174517
34437,7.5,2022-12-30,8.0,6.9,11675.0,7.05,BANKNIFTY05JAN2345700CE,09:15:00,12177,0.179501
34796,7.0,2022-12-30,7.3,6.3,32875.0,6.9,BANKNIFTY05JAN2345800CE,09:15:00,10651,0.184583
35155,6.55,2022-12-30,6.75,6.0,19350.0,6.2,BANKNIFTY05JAN2345900CE,09:15:00,4826,0.189624
35510,6.1,2022-12-30,6.1,5.2,435400.0,5.2,BANKNIFTY05JAN2346000CE,09:15:00,106877,0.194429
35895,4.9,2022-12-30,4.95,4.5,84100.0,4.5,BANKNIFTY05JAN2346500CE,09:15:00,51477,0.220890
36263,4.05,2022-12-30,4.15,3.8,392775.0,3.85,BANKNIFTY05JAN2347000CE,09:15:00,64576,0.246312
36635,3.75,2022-12-30,3.75,3.4,20850.0,3.65,BANKNIFTY05JAN2347500CE,09:15:00,19901,0.273780
36982,3.6,2022-12-30,3.65,3.35,39150.0,3.5,BANKNIFTY05JAN2348000CE,09:15:00,29277,0.301442
37314,3.5,2022-12-30,3.5,3.2,46275.0,3.2,BANKNIFTY05JAN2348500CE,09:15:00,37576,0.328756
37638,3.45,2022-12-30,3.5,3.0,313250.0,3.15,BANKNIFTY05JAN2349000CE,09:15:00,200152,0.355914

In [129]:
import py_vollib.black_scholes.greeks.analytical as greeks
from datetime import datetime

# Calculate delta for each call option
for index, row in call_option_data.iterrows():
    option_price = row['close']
    stock_price = float(row['close'])
    strike_price = float(row['symbol'].split('CE')[0][-5:])
    expiration_date_str = row['symbol'][9:16]
    expiration_date = datetime.strptime(expiration_date_str, '%d%b%y').date()
    current_date = datetime.strptime(row['date'], '%Y-%m-%d').date()
    time_to_expiration = (expiration_date - current_date).days / 365.0
    risk_free_rate = 0.05
    volatility = row['implied_volatility']
    
#     print(underlying_price, stock_price, strike_price, expiration_date, current_date, time_to_expiration)
    delta = greeks.delta('c', underlying_price, strike_price, time_to_expiration, risk_free_rate, volatility)
    delta_rounded = round(delta, 3)
    call_option_data.loc[index, 'delta'] = delta_rounded

print(call_option_data[['symbol', 'delta']])

                        symbol  delta
8599   BANKNIFTY05JAN2341300CE  0.982
9363   BANKNIFTY05JAN2341500CE  0.972
11712  BANKNIFTY05JAN2342000CE  0.927
12452  BANKNIFTY05JAN2342100CE  0.913
13038  BANKNIFTY05JAN2342200CE  0.897
13730  BANKNIFTY05JAN2342300CE  0.880
14434  BANKNIFTY05JAN2342400CE  0.860
15156  BANKNIFTY05JAN2342500CE  0.839
15907  BANKNIFTY05JAN2342600CE  0.815
16657  BANKNIFTY05JAN2342700CE  0.790
17408  BANKNIFTY05JAN2342800CE  0.763
18160  BANKNIFTY05JAN2342900CE  0.734
18912  BANKNIFTY05JAN2343000CE  0.972
19664  BANKNIFTY05JAN2343100CE  0.844
20416  BANKNIFTY05JAN2343200CE  0.759
21168  BANKNIFTY05JAN2343300CE  0.685
21920  BANKNIFTY05JAN2343400CE  0.616
22672  BANKNIFTY05JAN2343500CE  0.551
23423  BANKNIFTY05JAN2343600CE  0.490
24173  BANKNIFTY05JAN2343700CE  0.432
24924  BANKNIFTY05JAN2343800CE  0.378
25674  BANKNIFTY05JAN2343900CE  0.327
26414  BANKNIFTY05JAN2344000CE  0.280
27165  BANKNIFTY05JAN2344100CE  0.240
27819  BANKNIFTY05JAN2344200CE  0.203
28436  BANKNIFTY05JAN2344300CE  0.170
28950  BANKNIFTY05JAN2344400CE  0.143
29443  BANKNIFTY05JAN2344500CE  0.119
30100  BANKNIFTY05JAN2344600CE  0.097
30489  BANKNIFTY05JAN2344700CE  0.080
30872  BANKNIFTY05JAN2344800CE  0.067
31254  BANKNIFTY05JAN2344900CE  0.056
31630  BANKNIFTY05JAN2345000CE  0.047
32158  BANKNIFTY05JAN2345100CE  0.040
32536  BANKNIFTY05JAN2345200CE  0.034
32916  BANKNIFTY05JAN2345300CE  0.031
33297  BANKNIFTY05JAN2345400CE  0.027
33671  BANKNIFTY05JAN2345500CE  0.024
34063  BANKNIFTY05JAN2345600CE  0.022
34437  BANKNIFTY05JAN2345700CE  0.020
34796  BANKNIFTY05JAN2345800CE  0.018
35155  BANKNIFTY05JAN2345900CE  0.017
35510  BANKNIFTY05JAN2346000CE  0.015
35895  BANKNIFTY05JAN2346500CE  0.011
36263  BANKNIFTY05JAN2347000CE  0.009
36635  BANKNIFTY05JAN2347500CE  0.007
36982  BANKNIFTY05JAN2348000CE  0.007
37314  BANKNIFTY05JAN2348500CE  0.006
37638  BANKNIFTY05JAN2349000CE  0.005

In [130]:
call_option_data['delta_diff'] = abs(call_option_data['delta']-0.3)

In [131]:
call_option_data

,close,date,high,low,oi,open,symbol,time,volume,implied_volatility,delta,delta_diff
8599,2093.15,2022-12-30,2093.15,2093.15,1800.0,2093.15,BANKNIFTY05JAN2341300CE,09:15:00,26,0.200000,0.982,0.682
9363,1914.2,2022-12-30,1984.6,1850.0,53675.0,1850.0,BANKNIFTY05JAN2341500CE,09:15:00,1826,0.200000,0.972,0.672
11712,1430.5,2022-12-30,1494.25,1400.0,122725.0,1400.0,BANKNIFTY05JAN2342000CE,09:15:00,8577,0.200000,0.927,0.627
12452,1352.1,2022-12-30,1392.95,1300.0,14900.0,1300.0,BANKNIFTY05JAN2342100CE,09:15:00,176,0.200000,0.913,0.613
13038,1250.85,2022-12-30,1273.1,1246.85,29825.0,1246.85,BANKNIFTY05JAN2342200CE,09:15:00,1176,0.200000,0.897,0.597
13730,1158.45,2022-12-30,1207.25,1142.2,23125.0,1165.2,BANKNIFTY05JAN2342300CE,09:15:00,1101,0.200000,0.880,0.580
14434,1064.0,2022-12-30,1128.9,1064.0,23300.0,1072.3,BANKNIFTY05JAN2342400CE,09:15:00,1727,0.200000,0.860,0.560
15156,980.0,2022-12-30,1040.0,941.4,282250.0,941.4,BANKNIFTY05JAN2342500CE,09:15:00,27901,0.200000,0.839,0.539
15907,895.0,2022-12-30,946.8,805.35,108725.0,805.35,BANKNIFTY05JAN2342600CE,09:15:00,5276,0.200000,0.815,0.515
16657,813.6,2022-12-30,868.8,782.4,124000.0,782.4,BANKNIFTY05JAN2342700CE,09:15:00,12401,0.200000,0.790,0.490
17408,734.6,2022-12-30,788.05,722.3,169200.0,723.95,BANKNIFTY05JAN2342800CE,09:15:00,19627,0.200000,0.763,0.463
18160,659.9,2022-12-30,713.8,629.15,127325.0,635.0,BANKNIFTY05JAN2342900CE,09:15:00,34452,0.200000,0.734,0.434
18912,590.9,2022-12-30,638.0,550.0,993550.0,550.0,BANKNIFTY05JAN2343000CE,09:15:00,231678,0.054541,0.972,0.672
19664,525.6,2022-12-30,567.6,496.1,280325.0,554.85,BANKNIFTY05JAN2343100CE,09:15:00,95928,0.085583,0.844,0.544
20416,463.1,2022-12-30,500.0,419.95,440475.0,419.95,BANKNIFTY05JAN2343200CE,09:15:00,294502,0.097299,0.759,0.459
21168,405.4,2022-12-30,441.6,375.05,543150.0,375.05,BANKNIFTY05JAN2343300CE,09:15:00,503103,0.105204,0.685,0.385
21920,351.65,2022-12-30,384.6,320.9,382875.0,360.0,BANKNIFTY05JAN2343400CE,09:15:00,891278,0.110738,0.616,0.316
22672,304.3,2022-12-30,332.55,266.5,1274125.0,299.75,BANKNIFTY05JAN2343500CE,09:15:00,996528,0.115810,0.551,0.251
23423,260.45,2022-12-30,284.9,220.45,166925.0,221.6,BANKNIFTY05JAN2343600CE,09:15:00,503152,0.119480,0.490,0.190
24173,219.8,2022-12-30,241.8,182.4,223150.0,205.1,BANKNIFTY05JAN2343700CE,09:15:00,242703,0.121906,0.432,0.132
24924,184.9,2022-12-30,203.2,152.7,303650.0,170.0,BANKNIFTY05JAN2343800CE,09:15:00,237428,0.124447,0.378,0.078
25674,153.0,2022-12-30,169.05,116.6,196850.0,116.65,BANKNIFTY05JAN2343900CE,09:15:00,183652,0.126012,0.327,0.027
26414,125.55,2022-12-30,138.9,110.25,831550.0,120.0,BANKNIFTY05JAN2344000CE,09:15:00,475453,0.127445,0.280,0.020
27165,104.45,2022-12-30,113.9,53.35,214700.0,53.35,BANKNIFTY05JAN2344100CE,09:15:00,139077,0.130075,0.240,0.060
27819,85.3,2022-12-30,93.15,75.55,305750.0,79.1,BANKNIFTY05JAN2344200CE,09:15:00,159577,0.131798,0.203,0.097
28436,68.95,2022-12-30,75.55,53.85,200825.0,53.85,BANKNIFTY05JAN2344300CE,09:15:00,182026,0.133244,0.170,0.130
28950,56.45,2022-12-30,61.45,45.0,121850.0,45.0,BANKNIFTY05JAN2344400CE,09:15:00,123477,0.135481,0.143,0.157
29443,45.55,2022-12-30,50.7,40.0,845125.0,42.0,BANKNIFTY05JAN2344500CE,09:15:00,261603,0.137195,0.119,0.181
30100,36.15,2022-12-30,40.5,31.95,124525.0,38.35,BANKNIFTY05JAN2344600CE,09:15:00,108227,0.138418,0.097,0.203
30489,29.0,2022-12-30,33.55,27.0,124075.0,27.0,BANKNIFTY05JAN2344700CE,09:15:00,123903,0.140183,0.080,0.220
30872,23.95,2022-12-30,28.25,19.1,154925.0,25.05,BANKNIFTY05JAN2344800CE,09:15:00,71603,0.142961,0.067,0.233
31254,19.85,2022-12-30,22.0,18.05,62625.0,18.2,BANKNIFTY05JAN2344900CE,09:15:00,48478,0.145795,0.056,0.244
31630,16.45,2022-12-30,20.0,15.15,704250.0,20.0,BANKNIFTY05JAN2345000CE,09:15:00,213253,0.148562,0.047,0.253
32158,14.1,2022-12-30,19.0,13.65,37350.0,15.05,BANKNIFTY05JAN2345100CE,09:15:00,20927,0.152225,0.040,0.260
32536,12.1,2022-12-30,14.5,11.85,152750.0,12.05,BANKNIFTY05JAN2345200CE,09:15:00,43226,0.155797,0.034,0.266
32916,10.95,2022-12-30,12.7,8.55,85125.0,10.0,BANKNIFTY05JAN2345300CE,09:15:00,32951,0.160707,0.031,0.269
33297,9.85,2022-12-30,10.95,8.75,25400.0,8.75,BANKNIFTY05JAN2345400CE,09:15:00,37801,0.165300,0.027,0.273
33671,8.9,2022-12-30,9.35,7.55,284850.0,8.75,BANKNIFTY05JAN2345500CE,09:15:00,143126,0.169876,0.024,0.276
34063,8.1,2022-12-30,8.75,7.6,24375.0,8.0,BANKNIFTY05JAN2345600CE,09:15:00,15651,0.174517,0.022,0.278
34437,7.5,2022-12-30,8.0,6.9,11675.0,7.05,BANKNIFTY05JAN2345700CE,09:15:00,12177,0.179501,0.020,0.280
34796,7.0,2022-12-30,7.3,6.3,32875.0,6.9,BANKNIFTY05JAN2345800CE,09:15:00,10651,0.184583,0.018,0.282
35155,6.55,2022-12-30,6.75,6.0,19350.0,6.2,BANKNIFTY05JAN2345900CE,09:15:00,4826,0.189624,0.017,0.283
35510,6.1,2022-12-30,6.1,5.2,435400.0,5.2,BANKNIFTY05JAN2346000CE,09:15:00,106877,0.194429,0.015,0.285
35895,4.9,2022-12-30,4.95,4.5,84100.0,4.5,BANKNIFTY05JAN2346500CE,09:15:00,51477,0.220890,0.011,0.289
36263,4.05,2022-12-30,4.15,3.8,392775.0,3.85,BANKNIFTY05JAN2347000CE,09:15:00,64576,0.246312,0.009,0.291
36635,3.75,2022-12-30,3.75,3.4,20850.0,3.65,BANKNIFTY05JAN2347500CE,09:15:00,19901,0.273780,0.007,0.293
36982,3.6,2022-12-30,3.65,3.35,39150.0,3.5,BANKNIFTY05JAN2348000CE,09:15:00,29277,0.301442,0.007,0.293
37314,3.5,2022-12-30,3.5,3.2,46275.0,3.2,BANKNIFTY05JAN2348500CE,09:15:00,37576,0.328756,0.006,0.294
37638,3.45,2022-12-30,3.5,3.0,313250.0,3.15,BANKNIFTY05JAN2349000CE,09:15:00,200152,0.355914,0.005,0.295

In [132]:
import datetime as dt

put_option_data = df[df['symbol'].str.endswith('PE')].copy()
put_option_data['time_to_expiration'] = None

# Calculate time to expiration for each call option
for index, row in put_option_data.iterrows():
    symbol = row['symbol']
    expiration_date_str = symbol[9:16]
    expiration_date = dt.datetime.strptime(expiration_date_str, '%d%b%y').date()

    current_date_str = row['date']
    current_date = dt.datetime.strptime(current_date_str, '%Y-%m-%d').date()

    time_to_expiration = (expiration_date - current_date).days
    put_option_data.loc[index, 'time_to_expiration'] = time_to_expiration

put_option_data[['symbol', 'time_to_expiration']].head()

                       symbol time_to_expiration
0     BANKNIFTY05JAN2336500PE                  6
350   BANKNIFTY05JAN2337000PE                  6
677   BANKNIFTY05JAN2337500PE                  6
972   BANKNIFTY05JAN2338000PE                  6
1331  BANKNIFTY05JAN2338500PE                  6

In [133]:
put_option_data.head()

,close,date,high,low,oi,open,symbol,time,volume,time_to_expiration
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802,6
350,3.9,2022-12-30,4.95,3.9,248875.0,4.8,BANKNIFTY05JAN2337000PE,09:15:00,35501,6
677,4.75,2022-12-30,5.9,4.65,97800.0,5.75,BANKNIFTY05JAN2337500PE,09:15:00,22227,6
972,5.4,2022-12-30,6.65,5.3,307325.0,6.6,BANKNIFTY05JAN2338000PE,09:15:00,65901,6
1331,6.3,2022-12-30,7.55,6.3,482225.0,7.45,BANKNIFTY05JAN2338500PE,09:15:00,42626,6

In [134]:
put_option_data['implied_volatility'] = 0.2

for index, row in put_option_data.iterrows():
    option_price = float(row['close'])
    stock_price = float(underlying_price)
    strike_price = float(row['symbol'].split('PE')[0][-5:])
    expiration_date_str = row['symbol'][9:16]
    expiration_date = dt.datetime.strptime(expiration_date_str, '%d%b%y').date()
    current_date = dt.datetime.strptime(row['date'], '%Y-%m-%d').date()
    time_to_expiration = (expiration_date - current_date).days / 365.0
    risk_free_rate = 0.065  
    initial_guess = 0.2  # Initial estimate of implied volatility

    try:
        implied_volatility = iv.implied_volatility(option_price, stock_price, strike_price, time_to_expiration, risk_free_rate, 'p')
        if np.isnan(implied_volatility):
            continue
        put_option_data.loc[index, 'implied_volatility'] = implied_volatility
    except:
        continue

# Print the resulting DataFrame with implied volatility values
print(put_option_data[['symbol', 'implied_volatility']])

                        symbol  implied_volatility
0      BANKNIFTY05JAN2336500PE            0.525962
350    BANKNIFTY05JAN2337000PE            0.494414
677    BANKNIFTY05JAN2337500PE            0.468063
972    BANKNIFTY05JAN2338000PE            0.437570
1331   BANKNIFTY05JAN2338500PE            0.407903
1698   BANKNIFTY05JAN2339000PE            0.376925
2074   BANKNIFTY05JAN2339500PE            0.344996
2450   BANKNIFTY05JAN2339700PE            0.333243
2811   BANKNIFTY05JAN2339800PE            0.328171
3175   BANKNIFTY05JAN2339900PE            0.321506
3554   BANKNIFTY05JAN2340000PE            0.315448
3930   BANKNIFTY05JAN2340100PE            0.310544
4296   BANKNIFTY05JAN2340200PE            0.305000
4672   BANKNIFTY05JAN2340300PE            0.298895
5047   BANKNIFTY05JAN2340400PE            0.293196
5433   BANKNIFTY05JAN2340500PE            0.286971
5808   BANKNIFTY05JAN2340600PE            0.280770
6181   BANKNIFTY05JAN2340700PE            0.275497
6557   BANKNIFTY05JAN2340800PE            0.270394
6943   BANKNIFTY05JAN2340900PE            0.265266
7460   BANKNIFTY05JAN2341000PE            0.260456
7842   BANKNIFTY05JAN2341100PE            0.255052
8224   BANKNIFTY05JAN2341200PE            0.250214
8606   BANKNIFTY05JAN2341300PE            0.245983
8988   BANKNIFTY05JAN2341400PE            0.240882
9605   BANKNIFTY05JAN2341500PE            0.236922
10023  BANKNIFTY05JAN2341600PE            0.232998
10458  BANKNIFTY05JAN2341700PE            0.229171
10872  BANKNIFTY05JAN2341800PE            0.225927
11336  BANKNIFTY05JAN2341900PE            0.222017
12076  BANKNIFTY05JAN2342000PE            0.218111
12662  BANKNIFTY05JAN2342100PE            0.215131
13354  BANKNIFTY05JAN2342200PE            0.212709
14058  BANKNIFTY05JAN2342300PE            0.210763
14780  BANKNIFTY05JAN2342400PE            0.207819
15531  BANKNIFTY05JAN2342500PE            0.206392
16281  BANKNIFTY05JAN2342600PE            0.204270
17032  BANKNIFTY05JAN2342700PE            0.203929
17784  BANKNIFTY05JAN2342800PE            0.202709
18536  BANKNIFTY05JAN2342900PE            0.202496
19288  BANKNIFTY05JAN2343000PE            0.202442
20040  BANKNIFTY05JAN2343100PE            0.202724
20792  BANKNIFTY05JAN2343200PE            0.204058
21544  BANKNIFTY05JAN2343300PE            0.205712
22296  BANKNIFTY05JAN2343400PE            0.207750
23048  BANKNIFTY05JAN2343500PE            0.210399
23798  BANKNIFTY05JAN2343600PE            0.213822
24549  BANKNIFTY05JAN2343700PE            0.216552
25300  BANKNIFTY05JAN2343800PE            0.220834
26050  BANKNIFTY05JAN2343900PE            0.225956
26790  BANKNIFTY05JAN2344000PE            0.231295
27541  BANKNIFTY05JAN2344100PE            0.238294
28195  BANKNIFTY05JAN2344200PE            0.239201
28812  BANKNIFTY05JAN2344300PE            0.249007
29326  BANKNIFTY05JAN2344400PE            0.255868
29819  BANKNIFTY05JAN2344500PE            0.264556
30475  BANKNIFTY05JAN2344600PE            0.268998
31247  BANKNIFTY05JAN2344800PE            0.258810
32006  BANKNIFTY05JAN2345000PE            0.313660

In [138]:
# Calculate delta for each call option
for index, row in put_option_data.iterrows():
    option_price = row['close']
    stock_price = float(row['close'])
    strike_price = float(row['symbol'].split('PE')[0][-5:])
    expiration_date_str = row['symbol'][9:16]
    expiration_date = datetime.strptime(expiration_date_str, '%d%b%y').date()
    current_date = datetime.strptime(row['date'], '%Y-%m-%d').date()
    time_to_expiration = (expiration_date - current_date).days / 365.0
    risk_free_rate = 0.05
    volatility = row['implied_volatility']
    
#     print(underlying_price, stock_price, strike_price, expiration_date, current_date, time_to_expiration)
    delta = greeks.delta('p', underlying_price, strike_price, time_to_expiration, risk_free_rate, volatility)
    delta_rounded = round(delta, 3)
    put_option_data.loc[index, 'delta'] = delta_rounded

print(put_option_data[['symbol', 'delta']])

                        symbol  delta
0      BANKNIFTY05JAN2336500PE -0.004
350    BANKNIFTY05JAN2337000PE -0.004
677    BANKNIFTY05JAN2337500PE -0.006
972    BANKNIFTY05JAN2338000PE -0.007
1331   BANKNIFTY05JAN2338500PE -0.008
1698   BANKNIFTY05JAN2339000PE -0.010
2074   BANKNIFTY05JAN2339500PE -0.012
2450   BANKNIFTY05JAN2339700PE -0.014
2811   BANKNIFTY05JAN2339800PE -0.015
3175   BANKNIFTY05JAN2339900PE -0.015
3554   BANKNIFTY05JAN2340000PE -0.016
3930   BANKNIFTY05JAN2340100PE -0.017
4296   BANKNIFTY05JAN2340200PE -0.019
4672   BANKNIFTY05JAN2340300PE -0.020
5047   BANKNIFTY05JAN2340400PE -0.021
5433   BANKNIFTY05JAN2340500PE -0.022
5808   BANKNIFTY05JAN2340600PE -0.024
6181   BANKNIFTY05JAN2340700PE -0.025
6557   BANKNIFTY05JAN2340800PE -0.028
6943   BANKNIFTY05JAN2340900PE -0.030
7460   BANKNIFTY05JAN2341000PE -0.033
7842   BANKNIFTY05JAN2341100PE -0.035
8224   BANKNIFTY05JAN2341200PE -0.039
8606   BANKNIFTY05JAN2341300PE -0.043
8988   BANKNIFTY05JAN2341400PE -0.047
9605   BANKNIFTY05JAN2341500PE -0.052
10023  BANKNIFTY05JAN2341600PE -0.058
10458  BANKNIFTY05JAN2341700PE -0.065
10872  BANKNIFTY05JAN2341800PE -0.073
11336  BANKNIFTY05JAN2341900PE -0.082
12076  BANKNIFTY05JAN2342000PE -0.091
12662  BANKNIFTY05JAN2342100PE -0.103
13354  BANKNIFTY05JAN2342200PE -0.117
14058  BANKNIFTY05JAN2342300PE -0.132
14780  BANKNIFTY05JAN2342400PE -0.149
15531  BANKNIFTY05JAN2342500PE -0.169
16281  BANKNIFTY05JAN2342600PE -0.190
17032  BANKNIFTY05JAN2342700PE -0.214
17784  BANKNIFTY05JAN2342800PE -0.240
18536  BANKNIFTY05JAN2342900PE -0.269
19288  BANKNIFTY05JAN2343000PE -0.299
20040  BANKNIFTY05JAN2343100PE -0.331
20792  BANKNIFTY05JAN2343200PE -0.365
21544  BANKNIFTY05JAN2343300PE -0.399
22296  BANKNIFTY05JAN2343400PE -0.434
23048  BANKNIFTY05JAN2343500PE -0.468
23798  BANKNIFTY05JAN2343600PE -0.502
24549  BANKNIFTY05JAN2343700PE -0.535
25300  BANKNIFTY05JAN2343800PE -0.566
26050  BANKNIFTY05JAN2343900PE -0.595
26790  BANKNIFTY05JAN2344000PE -0.622
27541  BANKNIFTY05JAN2344100PE -0.646
28195  BANKNIFTY05JAN2344200PE -0.673
28812  BANKNIFTY05JAN2344300PE -0.691
29326  BANKNIFTY05JAN2344400PE -0.710
29819  BANKNIFTY05JAN2344500PE -0.726
30475  BANKNIFTY05JAN2344600PE -0.744
31247  BANKNIFTY05JAN2344800PE -0.793
32006  BANKNIFTY05JAN2345000PE -0.782

In [140]:
put_option_data['delta_diff'] = abs(put_option_data['delta']+0.3)
put_option_data

,close,date,high,low,oi,open,symbol,time,volume,time_to_expiration,implied_volatility,delta,delta_diff
0,3.55,2022-12-30,4.4,3.3,60900.0,3.95,BANKNIFTY05JAN2336500PE,09:15:00,34802,6,0.525962,-0.004,0.296
350,3.9,2022-12-30,4.95,3.9,248875.0,4.8,BANKNIFTY05JAN2337000PE,09:15:00,35501,6,0.494414,-0.004,0.296
677,4.75,2022-12-30,5.9,4.65,97800.0,5.75,BANKNIFTY05JAN2337500PE,09:15:00,22227,6,0.468063,-0.006,0.294
972,5.4,2022-12-30,6.65,5.3,307325.0,6.6,BANKNIFTY05JAN2338000PE,09:15:00,65901,6,0.437570,-0.007,0.293
1331,6.3,2022-12-30,7.55,6.3,482225.0,7.45,BANKNIFTY05JAN2338500PE,09:15:00,42626,6,0.407903,-0.008,0.292
1698,7.25,2022-12-30,8.35,7.15,736100.0,8.35,BANKNIFTY05JAN2339000PE,09:15:00,102827,6,0.376925,-0.010,0.290
2074,8.3,2022-12-30,8.9,7.45,451525.0,8.85,BANKNIFTY05JAN2339500PE,09:15:00,106651,6,0.344996,-0.012,0.288
2450,9.0,2022-12-30,10.55,7.95,43275.0,9.9,BANKNIFTY05JAN2339700PE,09:15:00,13551,6,0.333243,-0.014,0.286
2811,9.55,2022-12-30,10.95,8.85,29400.0,10.95,BANKNIFTY05JAN2339800PE,09:15:00,8003,6,0.328171,-0.015,0.285
3175,9.8,2022-12-30,12.05,6.35,21725.0,12.0,BANKNIFTY05JAN2339900PE,09:15:00,8503,6,0.321506,-0.015,0.285
3554,10.2,2022-12-30,11.0,8.25,735900.0,10.5,BANKNIFTY05JAN2340000PE,09:15:00,161302,6,0.315448,-0.016,0.284
3930,10.9,2022-12-30,16.4,9.05,19275.0,12.3,BANKNIFTY05JAN2340100PE,09:15:00,12227,6,0.310544,-0.017,0.283
4296,11.5,2022-12-30,11.55,10.0,26100.0,10.0,BANKNIFTY05JAN2340200PE,09:15:00,19828,6,0.305000,-0.019,0.281
4672,12.0,2022-12-30,13.05,7.35,56600.0,12.95,BANKNIFTY05JAN2340300PE,09:15:00,14227,6,0.298895,-0.020,0.280
5047,12.65,2022-12-30,12.65,11.25,72075.0,12.55,BANKNIFTY05JAN2340400PE,09:15:00,16302,6,0.293196,-0.021,0.279
5433,13.2,2022-12-30,15.0,10.25,563800.0,13.75,BANKNIFTY05JAN2340500PE,09:15:00,194653,6,0.286971,-0.022,0.278
5808,13.8,2022-12-30,13.8,10.2,35075.0,13.7,BANKNIFTY05JAN2340600PE,09:15:00,15753,6,0.280770,-0.024,0.276
6181,14.75,2022-12-30,19.25,10.8,50300.0,16.0,BANKNIFTY05JAN2340700PE,09:15:00,18902,6,0.275497,-0.025,0.275
6557,15.85,2022-12-30,22.85,13.1,84600.0,17.5,BANKNIFTY05JAN2340800PE,09:15:00,23227,6,0.270394,-0.028,0.272
6943,17.05,2022-12-30,19.0,15.0,49925.0,19.0,BANKNIFTY05JAN2340900PE,09:15:00,13052,6,0.265266,-0.030,0.270
7460,18.5,2022-12-30,18.9,14.35,761600.0,14.4,BANKNIFTY05JAN2341000PE,09:15:00,197751,6,0.260456,-0.033,0.267
7842,19.85,2022-12-30,21.9,15.6,94500.0,21.9,BANKNIFTY05JAN2341100PE,09:15:00,23353,6,0.255052,-0.035,0.265
8224,21.6,2022-12-30,22.1,18.0,187625.0,22.1,BANKNIFTY05JAN2341200PE,09:15:00,37452,6,0.250214,-0.039,0.261
8606,23.85,2022-12-30,29.55,18.05,311300.0,25.5,BANKNIFTY05JAN2341300PE,09:15:00,45251,6,0.245983,-0.043,0.257
8988,25.9,2022-12-30,31.2,20.5,203675.0,25.0,BANKNIFTY05JAN2341400PE,09:15:00,29053,6,0.240882,-0.047,0.253
9605,28.85,2022-12-30,29.7,22.0,600500.0,29.7,BANKNIFTY05JAN2341500PE,09:15:00,135128,6,0.236922,-0.052,0.248
10023,32.2,2022-12-30,35.0,25.0,221375.0,35.0,BANKNIFTY05JAN2341600PE,09:15:00,76251,6,0.232998,-0.058,0.242
10458,36.05,2022-12-30,38.5,29.95,183150.0,38.5,BANKNIFTY05JAN2341700PE,09:15:00,72627,6,0.229171,-0.065,0.235
10872,40.85,2022-12-30,40.85,23.1,321550.0,38.9,BANKNIFTY05JAN2341800PE,09:15:00,158553,6,0.225927,-0.073,0.227
11336,45.75,2022-12-30,45.75,36.55,163275.0,40.0,BANKNIFTY05JAN2341900PE,09:15:00,69677,6,0.222017,-0.082,0.218
12076,51.3,2022-12-30,55.0,38.5,1015000.0,55.0,BANKNIFTY05JAN2342000PE,09:15:00,216978,6,0.218111,-0.091,0.209
12662,58.5,2022-12-30,59.85,47.45,185725.0,51.0,BANKNIFTY05JAN2342100PE,09:15:00,65351,6,0.215131,-0.103,0.197
13354,67.3,2022-12-30,77.0,54.55,334275.0,76.0,BANKNIFTY05JAN2342200PE,09:15:00,69377,6,0.212709,-0.117,0.183
14058,77.9,2022-12-30,77.9,60.05,271325.0,77.75,BANKNIFTY05JAN2342300PE,09:15:00,74426,6,0.210763,-0.132,0.168
14780,88.7,2022-12-30,97.85,71.3,339250.0,97.85,BANKNIFTY05JAN2342400PE,09:15:00,108203,6,0.207819,-0.149,0.151
15531,103.05,2022-12-30,109.8,81.35,1450650.0,109.8,BANKNIFTY05JAN2342500PE,09:15:00,335353,6,0.206392,-0.169,0.131
16281,118.3,2022-12-30,129.5,98.9,439375.0,129.5,BANKNIFTY05JAN2342600PE,09:15:00,110103,6,0.204270,-0.190,0.110
17032,138.4,2022-12-30,150.0,113.0,614100.0,149.25,BANKNIFTY05JAN2342700PE,09:15:00,255752,6,0.203929,-0.214,0.086
17784,159.55,2022-12-30,159.95,135.05,550325.0,159.95,BANKNIFTY05JAN2342800PE,09:15:00,170126,6,0.202709,-0.240,0.060
18536,185.1,2022-12-30,190.0,144.35,374600.0,189.95,BANKNIFTY05JAN2342900PE,09:15:00,159378,6,0.202496,-0.269,0.031
19288,213.9,2022-12-30,213.9,181.95,1804275.0,200.0,BANKNIFTY05JAN2343000PE,09:15:00,534653,6,0.202442,-0.299,0.001
20040,246.5,2022-12-30,268.95,213.0,304100.0,268.95,BANKNIFTY05JAN2343100PE,09:15:00,193002,6,0.202724,-0.331,0.031
20792,284.6,2022-12-30,307.75,247.65,364825.0,250.05,BANKNIFTY05JAN2343200PE,09:15:00,311803,6,0.204058,-0.365,0.065
21544,326.9,2022-12-30,346.4,286.15,513050.0,346.4,BANKNIFTY05JAN2343300PE,09:15:00,435503,6,0.205712,-0.399,0.099
22296,373.6,2022-12-30,374.85,327.55,142175.0,374.85,BANKNIFTY05JAN2343400PE,09:15:00,611576,6,0.207750,-0.434,0.134
23048,425.2,2022-12-30,439.85,375.5,275050.0,439.85,BANKNIFTY05JAN2343500PE,09:15:00,427202,6,0.210399,-0.468,0.168
23798,482.0,2022-12-30,506.15,429.8,47175.0,500.0,BANKNIFTY05JAN2343600PE,09:15:00,96003,6,0.213822,-0.502,0.202
24549,540.6,2022-12-30,562.2,487.5,17650.0,534.95,BANKNIFTY05JAN2343700PE,09:15:00,30152,6,0.216552,-0.535,0.235
25300,605.8,2022-12-30,610.6,549.1,23875.0,610.6,BANKNIFTY05JAN2343800PE,09:15:00,19552,6,0.220834,-0.566,0.266
26050,675.75,2022-12-30,676.55,616.4,40350.0,645.45,BANKNIFTY05JAN2343900PE,09:15:00,5177,6,0.225956,-0.595,0.295
26790,748.8,2022-12-30,755.0,685.5,73625.0,755.0,BANKNIFTY05JAN2344000PE,09:15:00,20526,6,0.231295,-0.622,0.322
27541,827.7,2022-12-30,827.7,759.0,1475.0,793.95,BANKNIFTY05JAN2344100PE,09:15:00,3901,6,0.238294,-0.646,0.346
28195,896.25,2022-12-30,905.35,827.85,2300.0,879.25,BANKNIFTY05JAN2344200PE,09:15:00,1377,6,0.239201,-0.673,0.373
28812,984.8,2022-12-30,1078.8,931.2,1450.0,1078.8,BANKNIFTY05JAN2344300PE,09:15:00,701,6,0.249007,-0.691,0.391
29326,1069.0,2022-12-30,1069.0,1020.9,675.0,1049.5,BANKNIFTY05JAN2344400PE,09:15:00,201,6,0.255868,-0.710,0.410
29819,1158.05,2022-12-30,1160.5,1091.2,13900.0,1156.15,BANKNIFTY05JAN2344500PE,09:15:00,1576,6,0.264556,-0.726,0.426
30475,1240.5,2022-12-30,1240.5,1240.5,50.0,1240.5,BANKNIFTY05JAN2344600PE,09:15:00,26,6,0.268998,-0.744,0.444
31247,1378.25,2022-12-30,1378.25,1378.25,50.0,1378.25,BANKNIFTY05JAN2344800PE,09:15:00,26,6,0.258810,-0.793,0.493
32006,1626.65,2022-12-30,1626.65,1555.65,8250.0,1555.65,BANKNIFTY05JAN2345000PE,09:15:00,351,6,0.313660,-0.782,0.482